version: '3'

services:
       web1:
               image: web:v2 
               volumes: 
                   - web1:/var/www/html
               ports:
                   - 8080:80
               environment:
                       x: app1
       web2:
               image: web:v2
               volumes:
                   - web2:/var/www/html
               ports:
                   - 8081:3000
               environment:
                       x: app2
       web3:
               image: web:v2
               volumes:
                   - web3:/var/www/html
               ports:
                   - 8082:3000
               environment:
                       x: app3

volumes:
      web1:
      web2:
      web3:
